### ISSUE TITLE
ContourLines/data/points.geojson not found

### ISSUE THREAD

**Issue by giskernel** [HichamZouarhi/turf-ContourLines#1]
Getting 404 error while running the application at ContourLines/data/points.geojson

**Comment by hichamzouarhi** [comment]
Hi, I no longer maintain this repository since I found out that turfJS has already a plugin for creating contour lines, check it here ( https://github.com/Turfjs/turf/tree/master/packages/turf-isolines ).
Good luck

**Comment by giskernel** [comment]
Thanks Mate!
